### ISSUE TITLE
Términos a usar en traducciones

### ISSUE THREAD

**Issue by belohlavek** [pazguille/preact-www#12]
Habría que decidir cómo traducir términos técnicos como "Class components" y "High-Order Components" (entre otros). Quizás es mejor dejarlos en inglés, no estoy seguro.

Si elegimos traducirlos deberíamos mantener una referencia de términos y sus traducciones acordadas.

Ver también reactjs-hispano/react-es-docs#6

**Comment by pazguille** [comment]
@belohlavek , estoy de acuerdo. Me convence mantener esos nombres en ingles, ya que en el día a día usamos esos terminos. Qué te parece?

Por otro lado, lo haría en español neutro. La parte de /about lo trate de hacer de esta forma.

**Comment by belohlavek** [comment]
Perfecto, esta tarde elijo un issue, traduzco y mando PR 👍

**Comment by belohlavek** [comment]
Gracias por el push access, igual planeo mandar PRs asi hay un review previo!

**Comment by pazguille** [comment]
Te agregueécomo colaborador así trabajamos dentro del mismo repo.

**Comment by pazguille** [comment]
Sisi, pero lo manejamos dentro del mismo repo con branches asi lo mio tmb
tiene review :)
