### ISSUE TITLE
Add translation for "guide/differences-to-react.md"

### ISSUE THREAD

**Issue by pazguille** [pazguille/preact-www#2]

**Comment by belohlavek** [comment]
Habría que decidir cómo traducir términos técnicos como "Class components" y "High-Order Components" (entre otros). Quizás es mejor dejarlos en inglés, no estoy seguro.

Si elegimos traducirlos deberíamos mantener una referencia de términos y sus traducciones acordadas.

Ver también https://github.com/reactjs-hispano/react-es-docs/issues/6

**Comment by belohlavek** [comment]
Yo hoy me pongo con esto, no se a que hora, probablemente tarde 😱

**Comment by impronunciable** [comment]
Perdón que no vi los issues pero ya traduje parte de la guia

**Comment by belohlavek** [comment]
Woops, no pasa nada, te lo dejo asignado y yo me asigno otro  👍
