### ISSUE TITLE
Add translation for "guide/getting-started.md"

### ISSUE THREAD

**Issue by pazguille** [pazguille/preact-www#6]

**Comment by belohlavek** [comment]
Mine!

**Comment by belohlavek** [comment]
Ya lo traduje, mañana le doy una pasada de spellcheck y commiteo 👍

**Comment by belohlavek** [comment]
Pregunta de un github noob: que pasó acá? https://github.com/pazguille/preact-www/commit/050d96ebed00090bf967095a2f5a5df8d85d1541

**Comment by impronunciable** [comment]
@belohlavek a qué te referís con qué pasó?

**Comment by belohlavek** [comment]
@impronunciable me faltaría comprender algún concepto de git.
Yo localmente hice un `pull` para obtener los últimos cambios de la branch, después hice un nuevo `commit` con [mis cambios](https://github.com/pazguille/preact-www/commit/69bbbf8eae04e01ef4bcccff692220c0d7e42626) y pushee a la branch correspondiente. En github figuran dos commits: uno es el esperado (creado por mi) y el otro es un merge que no sabría a partir de qué fue generado (el concepto general de merge lo tengo claro).

**Comment by impronunciable** [comment]
Si en el merge no tuviste conflictos deberia estar todo bien. Igual mirate el diff para ver que no pasó nada raro :)

**Comment by belohlavek** [comment]
Si no entiendo mal, ese merge sería de la remote branch a mi local. Pero me extraña que eso figure en el historial de commits en Github. Lo comento porque da a entender que yo realicé cambios sobre archivos que en realidad nunca toqué (son los cambios de ustedes).

---

En otras noticias: @pazguille, me di cuenta que usamos un par de palabras distintas en la tabla de lifecycle-methods. Después corrijo lo mío para que esté alineado con lo tuyo (y con todo lo demás).
